--SELECT DISTINCT replacement_cost FROM film;
--SELECT COUNT(DISTINCT replacement_cost) FROM film;
--SELECT DISTINCT title FROM film WHERE title lIKE 'T%' AND rating = 'G';
--SELECT DISTINCT country FROM country WHERE country lIKE '_____';
--SELECT DISTINCT city FROM city WHERE city LIKE 'R%';